// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

#![doc = include_str!("../README.md")]
#![allow(dead_code)]
#![allow(unused_imports)]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]

pub mod clients;
mod generated;
mod parsers;
mod pipeline;
pub(crate) mod streams;
pub use clients::*;
pub use parsers::*;
pub mod models;

pub mod client_impl;
pub use client_impl::*;
pub mod model_extensions;
pub mod options_helpers;
pub mod partitioned_transfer;
pub mod transfer_validation;
